# Generated by Django 3.0.7 on 2020-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200616_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professions',
            name='profession_name',
            field=models.CharField(choices=[('OT', 'Others'), ('WD', 'Web Developer'), ('SE', 'Software Enginer'), ('ST', 'Student'), ('DA', 'Data Analysts'), ('DS', 'Data Scientiest')], max_length=2),
        ),
    ]
