# Generated by Django 3.0.7 on 2020-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200616_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='documents_type',
            field=models.CharField(choices=[('ID', 'Identity Card'), ('PP', 'Passport'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='professions',
            name='profession_name',
            field=models.CharField(choices=[('SE', 'Software Enginer'), ('ST', 'Student'), ('DA', 'Data Analysts'), ('WD', 'Web Developer'), ('DS', 'Data Scientiest'), ('OT', 'Others')], max_length=2),
        ),
    ]
